### ISSUE TITLE
Toggled rainfall and game crashed

### ISSUE THREAD

**Issue by hugonoss** [TSSN/Twisted-Tweaks#13] opened 2019-07-10 03:59 UTC
I toggled downfall in a taiga biome while testing a custom modpack and the game crashed.

Crash log: https://paste.dimdev.org/damakejupi.mccrash

**Comment by MindlessPuppetz** [comment] 2019-07-19 00:06
Have had two devs look into this and they cannot figure out exactly what has happened here. I would suggest you remove all mods and add them in one at a time to see which file is altering the behavior of our mod and causing the crash.

Closing for now as we do not believe this is something on our end causing the issue.

**Closed as completed by MindlessPuppetz** 2019-07-19 00:06 UTC

**Comment by artdude543** [comment] 2019-07-19 00:07
I believe this is being caused by a core mod tampering with potion effects. If ever stumble upon who is doing it, I could look into it more :)
